db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=verysecret
        - MYSQL_USER=course
        - MYSQL_PASSWORD=5566
        - MYSQL_DATABASE=course
    volumes:
        - ./NTHU_Course/mysql_charset.ini:/etc/mysql/conf.d/charset.cnf
web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    links:
        - db
    environment:
        - DJANGO_SETTINGS_MODULE=NTHU_Course.settings.docker
