db:
    image: mysql
    env_file:
        - .env
    volumes:
        - ./NTHU_Course/mysql_charset.ini:/etc/mysql/conf.d/charset.cnf
web:
    build: .
    command: sh start.sh
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    links:
        - db
    environment:
        - DJANGO_SETTINGS_MODULE=NTHU_Course.settings.docker
